version: "3"

services:
  reviewbot:
    build: .
    container_name: reviewbot
    command: python3 reviewbot/app.py
    env_file: ./.env
    volumes:
      - .:/app
    depends_on:
      - db

  salesbot:
    build: .
    container_name: salesbot
    command: python3 salebot/app.py
    env_file: ./.env
    volumes:
      - .:/app
    depends_on:
      - db

  admin:
    build: .
    container_name: admin
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:14
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - DJANGO_SETTINGS_MODULE=orm.settings

volumes:
  postgres_data:
