# Generated by Django 5.0.4 on 2024-07-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Xan Decor', max_length=255, verbose_name='Name')),
                ('sd_id', models.CharField(default='d0_5', max_length=255, unique=True, verbose_name='SD ID')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.CharField(max_length=255, unique=True, verbose_name='Product SD ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
            ],
            options={
                'verbose_name': 'Stock product',
                'verbose_name_plural': 'Stock products',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sd_id', models.CharField(max_length=255, unique=True, verbose_name='SD ID')),
            ],
            options={
                'verbose_name': 'WareHouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='WareHouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixod', models.IntegerField(default=0, verbose_name='Prixod')),
                ('sold', models.IntegerField(default=0, verbose_name='Sold')),
                ('ostatok', models.IntegerField(default=0, verbose_name='Ostatok')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesdoctorbot.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesdoctorbot.stockproduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesdoctorbot.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse product',
                'verbose_name_plural': 'Warehouse products',
                'unique_together': {('warehouse', 'product', 'category')},
            },
        ),
    ]
