# Generated by Django 5.0.4 on 2024-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesdoctorbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='arrivel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrivel date'),
        ),
    ]
