# Generated by Django 5.0.4 on 2024-07-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesdoctorbot', '0006_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
