# Generated by Django 5.0.4 on 2024-08-02 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesdoctorbot', '0008_store_uuid_warehouse_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salesdoctorbot.warehouse'),
            preserve_default=False,
        ),
    ]
