# Generated by Django 5.0.4 on 2024-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0010_alter_sale_purchase_date_delete_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
