# Generated by Django 5.0.4 on 2024-06-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0011_alter_sale_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
