# Generated by Django 5.0.4 on 2024-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0012_sale_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
