# Generated by Django 5.0.4 on 2024-06-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0013_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deadline',
            field=models.DateField(blank=True, help_text='Deadline for money return', null=True),
        ),
    ]
