# Generated by Django 5.0.4 on 2024-07-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0014_sale_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='orm_app.product')),
            ],
        ),
    ]
