# Generated by Django 5.0.4 on 2024-07-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0016_telegramgroup_discountevent_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountevent',
            name='discount_text',
        ),
        migrations.AddField(
            model_name='discountevent',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
