# Generated by Django 5.0.4 on 2024-07-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0017_remove_discountevent_discount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountevent',
            name='report_count',
            field=models.IntegerField(default=60),
        ),
    ]
