# Generated by Django 5.0.4 on 2024-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0018_discountevent_report_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountevent',
            name='discount',
            field=models.TextField(),
        ),
    ]
